spring:
  jpa:
    generate-ddl: false
    show-sql: true

server:
  port: 80  
  servlet:
    context-path: /
---
kakao:
  url: https://dapi.kakao.com/v3/search/book
  authorization: KakaoAK ebbf17292b0b2dc77648c22e77571ef3
---
naver:
  url: https://openapi.naver.com/v1/search/book.json
  clientId: 7DR4iBTS4REgJnj4955i
  clientSecret: XxLljnw7qJ
server:
  port: 80 

---
logging:
  config: classpath:logback-spring.xml
  path: logs/
  level:
    root: INFO
    org.springframework.core: INFO
    org.springframework.beans: INFO
    org.springframework.context: INFO
    org.springframework.web: INFO
    #org.springframework.data: INFO
    org.apache.http: INFO
    org.apache.catalina: INFO
    org.apache.coyote: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  